
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzxgsfvchitaariayuas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6eGdzZnZjaGl0YWFyaWF5dWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTA3MDEsImV4cCI6MjA1NTg2NjcwMX0.BvhHxyeqH2CCmghavjgS6bSXqHnSII6i__09154-pFg";

// Define development and production URLs
const isDevelopment = import.meta.env.DEV;
const siteUrl = isDevelopment 
  ? window.location.origin
  : 'https://yourusername.github.io/your-repo-name'; // Replace with your actual GitHub Pages URL

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Use the appropriate URL based on environment
      // This helps with authentication redirects
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  }
);
